### ISSUE TITLE
Dark Gyfte can't benefit from +HP%

### ISSUE THREAD

**Issue by taltamir** [Ezandora/Voting-Booth#3]
In dark gyfte the +HP% doesn't work, don't select it unless it is the only non negative choice. (since -ML is incorrectly marked as a positive choice, if it shows up you will obviously not want to choose it, even if it means taking the useless +HP%, at least +HP% is not harmful)

**Comment by MatthewDarling** [comment]
I think this is closed based on 55dc7a30a3fbdf0c4d533bd460ed6a56a871fac6 🎉
